extern int color[64];
extern int piece[64];
extern int possible[100][2];
extern int offset[30];
extern int totaloffs;
extern int player;
extern int opponent;
extern int castle;
extern int ep;
extern int fifty;
extern int ply;
extern int current;
extern int max_time;
extern int max_depth;
extern int start_time;
extern int stop_time;
extern int nodes;
extern bool white_short_castle;
extern bool white_long_castle;
extern bool black_short_castle;
extern bool black_long_castle;
extern long long hashing;
extern long long hash_piece[2][6][64];
extern long long hash_side;
extern long long hash_ep[64];
extern int hashcount;
extern long long hashes[1000000];
extern int hasheval[1000000];
extern int hashdepth[1000000];
extern int hashtype[1000000];
extern char piece_letter[6];
extern int start_color[64];
extern int start_piece[64];
extern int playcount;
extern int legalcount;
extern int captcount;
extern int validcount;
